import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Section from "./components/Section";
import ContentSection from './components/ContentSection';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const backgroundStyles = {
  backgroundImage: "url('/Assets/background/first.png') !important",
  backgroundSize: "cover !important",
  backgroundPosition: "center !important",
  backgroundRepeat: "no-repeat !important",
  minHeight: "100vh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={backgroundStyles}
      >

        <div className="navbar_container flex justify-center w-full">
          <div className="navbar_search w-full max-w-md">
            <input type="text" className="navbar_input" placeholder="Search..." />
          </div>
        </div>


        <div className="container_content flex justify-center w-full text-amber-50">
          <div className=".titulo_container_sections">

            <Section title="Web">
            </Section>

            <Section title="Desktop">
            </Section>
            <Section title="Mobile">
            </Section>
          </div>
        </div>
        {children}
      </body>
    </html >
  );
}
